version: "3"
services:
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
      - POSTGRES_HOST=localhost
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose
